name: Tests

on:
  pull_request:
  push:

jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]
        python-version: [3.11, 3.12, 3.13]
    name: Tests for Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Set fortran compiler on macOS
        if: startsWith(matrix.os, 'macos')
        run: |
          echo "PATH=$(brew --prefix gfortran)/bin:$PATH" >> $GITHUB_ENV

      - name: Install package
        run: |
          echo "FORTRAN: $(which gfortran)"
          python -m pip install .[test] -v

      - name: Test package
        run: python -m pytest
